export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ASSET_FILE_REQUIRED: 'ASSET_FILE_REQUIRED',
  ASSET_UNSUPPORTED_TYPE: 'ASSET_UNSUPPORTED_TYPE',
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  CHARACTER_NOT_FOUND: 'CHARACTER_NOT_FOUND',
  CHARACTER_DUPLICATE_NOT_IMPLEMENTED: 'CHARACTER_DUPLICATE_NOT_IMPLEMENTED',
  MODEL_CONFIG_NOT_FOUND: 'MODEL_CONFIG_NOT_FOUND',
  MODEL_CONFIG_NAME_EXISTS: 'MODEL_CONFIG_NAME_EXISTS',
  PERSONA_NOT_FOUND: 'PERSONA_NOT_FOUND',
  PERSONA_NAME_EXISTS: 'PERSONA_NAME_EXISTS',
  PROMPT_PRESET_NOT_FOUND: 'PROMPT_PRESET_NOT_FOUND',
  PROMPT_PRESET_NAME_EXISTS: 'PROMPT_PRESET_NAME_EXISTS'
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES] | (string & {});
